
import os
import glob
import numpy as np
import cv2
import sys
 
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, PROJECT_ROOT)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    from astropy.io import fits
except ImportError:
    import minifits as fits  # type: ignore  # test-environment shim only; see minifits.py
 
from lunar_limb import find_lunar_limb
 
INPUT_DIR = os.path.join(PROJECT_ROOT, "data/processed/calibrated_lights")
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "data/processed/aligned_lights")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def _copy_satmask_unwarped(src_path, out_path):
    """Copies the per-pixel saturation sidecar mask if generated by calibration."""
    import shutil
    mask_path = src_path.replace(".fits", "_satmask.npy")
    if os.path.exists(mask_path):
        out_mask_path = out_path.replace(".fits", "_satmask.npy")
        shutil.copy(mask_path, out_mask_path)


def process_alignment():
    files = sorted(glob.glob(f"{INPUT_DIR}/*.fits"))
    if not files:
        print(f"[-] No FITS files found in {INPUT_DIR}")
        return
 
    print(f"[+] Aligning {len(files)} frames via Hough limb detection...")
 
    ref_data = np.asarray(fits.getdata(files[0]), dtype=np.float32)
    ref_hdr = fits.getheader(files[0])
    ref_x, ref_y, ref_r, ref_ok = find_lunar_limb(ref_data)
 
    if not ref_ok:
        print(f"[!] WARNING: could not reliably find the lunar limb in the FIRST "
              f"frame ({os.path.basename(files[0])}), which is used as the alignment "
              f"reference for everything else. Falling back to frame geometric center "
              f"-- check this frame manually if the final result looks off-center.")
 
    print(f"[+] Master Reference: Center=(X={ref_x:.2f}, Y={ref_y:.2f}) Radius={ref_r:.1f}px "
          f"[{'measured' if ref_ok else 'FALLBACK: not confidently measured'}]")
 
    out_ref = os.path.join(OUTPUT_DIR, os.path.basename(files[0]))
    fits.PrimaryHDU(data=ref_data, header=ref_hdr).writeto(out_ref, overwrite=True)
    _copy_satmask_unwarped(files[0], out_ref)
 
    last_good_x, last_good_y = ref_x, ref_y
    n_fallback = 0
 
    for path in files[1:]:
        data = np.asarray(fits.getdata(path), dtype=np.float32)
        hdr = fits.getheader(path)
 
        cx, cy, r_found, ok = find_lunar_limb(data)
 
        if not ok:
            print(f"  -> [!] {os.path.basename(path)}: limb not confidently found, "
                  f"using last known good position ({last_good_x:.2f},{last_good_y:.2f}) "
                  f"as a fallback rather than guessing. INSPECT THIS FRAME -- it may be "
                  f"corrupted, blank, or have an unusual exposure.")
            cx, cy = last_good_x, last_good_y
            n_fallback += 1
        else:
            last_good_x, last_good_y = cx, cy
 
        dx, dy = float(ref_x - cx), float(ref_y - cy)
 
        M = np.array([[1.0, 0.0, dx], [0.0, 1.0, dy]], dtype=np.float32)
        h, w = int(data.shape[0]), int(data.shape[1])
 
        aligned_data = cv2.warpAffine(
            src=data,
            M=M,
            dsize=(w, h),
            flags=cv2.INTER_LANCZOS4,
            borderMode=cv2.BORDER_CONSTANT,
            borderValue=0.0
        )
 
        out_name = os.path.join(OUTPUT_DIR, os.path.basename(path))
        fits.PrimaryHDU(data=aligned_data, header=hdr).writeto(out_name, overwrite=True)
        flag = "" if ok else "  [FALLBACK POSITION USED]"
        print(f"  -> Aligned {os.path.basename(path)} (dx={dx:+.2f}, dy={dy:+.2f}, "
              f"r={r_found:.1f}px){flag}")
 
    if n_fallback:
        print(f"\n[!] {n_fallback} frame(s) used fallback alignment. Review the warnings "
              f"above before trusting the final composite.")
    print(f"[+] Alignment complete. Saved to {OUTPUT_DIR}.") 
if __name__ == "__main__":
 
    process_alignment()
 